"""Rewrite ``golden_tools.txt`` from the live catalog.

Run only when a tool-name change is intended and will be reviewed::

    DATABASE_URL=... SECRET_KEY=... .venv/bin/python -m tests.mcp.regenerate_golden
"""

from __future__ import annotations

from pathlib import Path

from app_main import app
from src.mcp_server.registry import get_registry

HEADER = (
    "# MCP tool contract: name<TAB>method<TAB>path, sorted by name.\n"
    "# Generated by tests/mcp/regenerate_golden.py. A diff here is a breaking\n"
    "# change for every connected client — review it, do not rubber-stamp it.\n"
)


def main() -> None:
    registry = get_registry(app)
    target = Path(__file__).with_name("golden_tools.txt")
    body = "".join(f"{name}\t{method}\t{path}\n" for name, method, path in registry.golden_triples())
    target.write_text(HEADER + body)
    print(f"Wrote {len(registry.golden_triples())} tools to {target}")


if __name__ == "__main__":
    main()
